### ISSUE TITLE
[BUG] Supplementary Information C04-C09 not rendered in HTML

### ISSUE THREAD

**Issue by stiebitzhofer** [thematerials-network/EN10168-schemas#39]
**Describe the bug**
The section `SupplementaryInformation` with the fields `C04-C09` are not rendered in HTML.

**To Reproduce**
1. Compare the HTML and PDF rendering of `test/fixtures/valid_certificate_4.json`.

**Expected behavior**
Supplementary information is rendered on HTML the same way as on PDF.

**Comment by eamon0989** [comment]
I've investigated this, the `SupplementaryInformation` section is missing in `inspection.hbs`. The fix is to add the following snippet to line 279.

```hbs
{{#ifEqual @key "SupplementaryInformation"}}
      <h3 class="third-level-title">
        {{ i18n "SupplementaryInformation" "otherFields" ../CertificateLanguages }}
      </h3>
      <table class="main-table">
        <tbody>
          {{#each this}}
            <tr class="table-rows">
              <th class="table-headers" colspan="2">{{@key}} {{this.Key}}</th>
              <td class="table-cells">
                {{localizeValue this.Value this.Type ../../CertificateLanguages.[0]}}
                {{this.Unit}}
              </td>
              <td class="table-cells">{{this.Interpretation}}</td>
            </tr>
          {{/each}}
        </tbody>
      </table>
    {{/ifEqual}}
```

I can fix it once I get back from holidays as a script would need to be created that would allow you to use a local filepath for the `inspection.hbs` partial for testing and the `ci` run, then once there is a new release, it should automatically update to use the remote path.
